# Generated by Django 5.2.17 on 2026-08-07 01:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('video_file', models.FileField(upload_to='uploads/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'mkv'])])),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnails/')),
                ('hls_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('hls_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='idx_videos_created_at'), models.Index(fields=['category'], name='idx_videos_category')],
            },
        ),
    ]
