# Generated by Django 5.2.17 on 2026-08-07 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(choices=[('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], max_length=10)),
                ('playlist_path', models.CharField(blank=True, default='', max_length=255)),
                ('segment_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='video_app.video')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('video', 'resolution'), name='uq_variant_video_resolution')],
            },
        ),
    ]
